package br.com.nsfatima.calendario.api.error;

public enum ErrorCodes {
    VALIDATION_ERROR,
    VALIDATION_REQUIRED_FIELD,
    VALIDATION_FIELD_INVALID,
    VALIDATION_ENUM_VALUE_INVALID,
    VALIDATION_UNKNOWN_FIELD,
    AUTH_REQUIRED,
    AUTH_INVALID,
    ACCESS_DENIED,
    ROLE_SCOPE_INVALID,
    AUTHZ_SOURCE_UNAVAILABLE,
    SESSION_EXPIRED,
    RESOURCE_NOT_FOUND,
    EVENT_NOT_FOUND,
    FORBIDDEN,
    APPROVAL_REQUIRED,
    APPROVAL_NOT_FOUND,
    APPROVAL_ALREADY_DECIDED,
    APPROVAL_EXECUTION_FAILED,
    INVALID_STATUS_TRANSITION,
    CONFLICT,
    CALENDAR_CONFLICT,
    IDEMPOTENCY_KEY_CONFLICT,
    DOMAIN_RULE_VIOLATION
}
