package br.com.nsfatima.calendario.api.error;

public enum ErrorCodes {
    VALIDATION_ERROR,
    VALIDATION_REQUIRED_FIELD,
    VALIDATION_FIELD_INVALID,
    VALIDATION_ENUM_VALUE_INVALID,
    VALIDATION_UNKNOWN_FIELD,
    AUTH_REQUIRED,
    ACCESS_DENIED,
    RESOURCE_NOT_FOUND,
    EVENT_NOT_FOUND,
    FORBIDDEN,
    APPROVAL_REQUIRED,
    CONFLICT,
    CALENDAR_CONFLICT,
    IDEMPOTENCY_KEY_CONFLICT,
    DOMAIN_RULE_VIOLATION
}
